## Tutorial 1: Introduction to PyTorch
lien = https://lightning.ai/docs/pytorch/stable/notebooks/course_UvA-DL/01-introduction-to-pytorch.html

In [1]:
import time

import matplotlib.pyplot as plt

%matplotlib inline
import matplotlib_inline.backend_inline
import numpy as np
import torch
import torch.nn as nn
import torch.utils.data as data
from matplotlib.colors import to_rgba
from torch import Tensor
from tqdm.notebook import tqdm  # Progress bar

matplotlib_inline.backend_inline.set_matplotlib_formats("svg", "pdf") 

In [2]:
# vérifier sa version
print("Using torch", torch.__version__)

Using torch 2.1.0+cpu


In [3]:
#permettre au code d'être reporductible 
torch.manual_seed(42)  # Setting the seed

## Créer un tenseur

In [6]:
# Solution 1 : 
X = Tensor(2, 3, 4)
print(X)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


La fonction torch.Tensor allocates la mémoire pour le tenseur souhaité, mais réutilise toutes les valeurs qui ont déjà été dans la mémoire. Pour affecter directement des valeurs au tenseur lors de l'initialisation, il existe de nombreuses alternatives, dont:



torch.zeros: Crée un tenseur rempli de zéros

torch.ones: Crée un tenseur rempli de ceux-là

torch.rand: Crée un tenseur avec des valeurs aléatoires échantillonnées uniformément entre 0 et 1

torch.randn: Crée un tenseur avec des valeurs aléatoires échantillonnées à partir d'une distribution normale avec la moyenne 0 et la variance 1

torch.arange: Crée un tenseur contenant les valeurs N,N+1,N+2,...,M

torch.Tensor(liste d'intrants): Crée un tenseur à partir des éléments de liste que vous fournissez


In [7]:
# Create a tensor from a (nested) list
x = Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


## Tenseur à Numpy, et Numpy à Tensor


In [12]:
# numpy -> tenseur 
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [13]:
# tenseur -> numpy
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


## Opération


In [14]:
#Aléatoire 

x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)

print("X1", x1)
print("X2", x2)


X1 tensor([[0.9408, 0.1332, 0.9346],
        [0.5936, 0.8694, 0.5677]])
X2 tensor([[0.7411, 0.4294, 0.8854],
        [0.5739, 0.2666, 0.6274]])


In [17]:
#Additionner terme par terme 

x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952]])
X2 (before) tensor([[0.0050, 0.3068, 0.1165],
        [0.9103, 0.6440, 0.7071]])
X1 (after) tensor([[0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952]])
X2 (after) tensor([[0.7941, 0.5882, 0.9051],
        [1.4997, 1.3979, 0.9024]])


In [26]:
# Rearranger 

x1 = torch.rand(2, 3)
print("X1 (before)", x1)
x1 = x1.view(6, 1)
print("X1 (after)", x1)

X1 (before) tensor([[0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725]])
X1 (after) tensor([[0.7860],
        [0.1115],
        [0.2477],
        [0.6524],
        [0.6057],
        [0.3725]])


In [27]:
x1 = x1.permute(1, 0)  # Swapping dimension 0 and 1
print("X", x1)


X tensor([[0.7860, 0.1115, 0.2477, 0.6524, 0.6057, 0.3725]])


D'autres opérations couramment utilisées incluent les multiplications matricielles, qui sont essentielles pour les réseaux neuronaux. Très souvent, nous avons un vecteur d'entrée\mathbf{x}, qui est transformé à l'aide d'une matrice de poids apprise\mathbf{W}. Il y a plusieurs façons et fonctions pour effectuer la multiplication matricielle, dont on énumère quelques-unes ci-dessous:

    torch.matmul: Effectue le produit de la matrice sur deux tenseurs, où le comportement spécifique dépend des dimensions. Si les deux entrées sont des matrices (protenseurs de 2 dimensions), elles réalisent le produit de matrice standard. Pour les entrées de dimension supérieure, la fonction prend en charge la diffusion (pour plus de détails, voir la documentation). Peut également être écrit sous la forme d'un a @ b, à l'instar de numpy.

    torch.mm: Effectue le produit matriciel sur deux matrices, mais ne supporte pas la diffusion (voir documentation)

    torch.bmm: Effectue le produit de la matrice avec une dimension de lot de support. Si le premier tenseur Test de forme (b\times n\times m), et le deuxième tenseur R(b\times m\times p), la sortie Oest de forme (b\times n\times p), et a été calculée en effectuant bdes multiplications matricielles des sous-matrices de TRet: O_i = T_i @ R_i

    torch.einsum: Effectue des multiplications de matrices et plus (c'est-à-dire des sommes de produits) en utilisant la convention de sommation d'Einstein. L'explication de la somme d'Einstein peut être trouvée dans l'assignation 1.


In [28]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

W = torch.arange(9).view(3, 3)  # We can also stack multiple operations in a single line
print("W", W)

h = torch.matmul(x, W)  # Verify the result by calculating it by hand too!
print("h", h)

X tensor([[0, 1, 2],
        [3, 4, 5]])
W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
h tensor([[15, 18, 21],
        [42, 54, 66]])


## Calcul dynamique et retropropagation


In [30]:
#La première chose que nous devons faire est de préciser quels tenseurs nécessitent des gradients. 
#Par défaut, lorsque nous créons un tenseur, il ne nécessite pas de gradients.


x = torch.ones((3,))
print(x.requires_grad)
x.requires_grad_(True)
print(x.requires_grad)

False
True


In [41]:
x = torch.arange(3, dtype=torch.float32, requires_grad=True)  # Only float tensors can have gradients
print("X", x)

X tensor([0., 1., 2.], requires_grad=True)


y = \frac{1}{|x|}\sum_i\left[(x_i+2)^2+3 \right]

In [42]:
a = x + 2
b = a**2
c = b + 3
y = c.mean()
print("Y", y)

Y tensor(12.6667, grad_fn=<MeanBackward0>)


In [43]:
y.backward()
#Désormais c'est x.grad qui contient la dérivé de y par rapport à x 

In [44]:
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])


## GPU 

In [50]:
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")

Is the GPU available? False


In [51]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Device cpu


## Modèle

In [48]:
# modèle de base 
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        # Some init for my module

    def forward(self, x):
        # Function for performing the calculation of the module.
        pass


In [ ]:
# modele avec une couche une couche dense (linear)
class SimpleClassifier(nn.Module):
    def __init__(self, num_inputs, num_hidden, num_outputs):
        super().__init__()
        # Initialize the modules we need to build the network
        self.linear1 = nn.Linear(num_inputs, num_hidden)
        self.act_fn = nn.Tanh()
        self.linear2 = nn.Linear(num_hidden, num_outputs)

    def forward(self, x):
        # Perform the calculation of the model to determine the prediction
        x = self.linear1(x)
        x = self.act_fn(x)
        x = self.linear2(x)
        return x